name: estate
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  
  #API
  http: ^1.1.0
  http_parser: ^4.0.2
  #Network
  connectivity_plus: ^6.0.3
  #JWT Token
  shared_preferences: ^2.2.2
  #State Management
  provider: ^6.1.4
  # UI
  flutter_rating_bar: ^4.0.1
  #Media
  image_picker: ^1.0.8
  #Logger
  logger: ^2.5.0
  #AI Entegration
  google_generative_ai: ^0.4.6


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true


  assets:
    - assets/images/

